spring:
  datasource:
#    url: jdbc:h2:~/querydsl # H2(Embedded)
    url: jdbc:h2:mem:querydsl # H2(In-Memory)
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  logging.level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

  # H2 Setting Info
  h2:
    console:
      enabled: true  # H2 Console
      path: /h2-console  # H2 Console Path
